"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var path = require("path");
var merge_graphql_schemas_1 = require("merge-graphql-schemas");
console.log(__dirname);
var typesArray = merge_graphql_schemas_1.fileLoader(path.join(__dirname, '**/**.graphql'));
var resolversArray = merge_graphql_schemas_1.fileLoader(path.join(__dirname, '**/resolvers.js'));
console.log(merge_graphql_schemas_1.mergeResolvers(resolversArray));
exports.typeDefs = merge_graphql_schemas_1.mergeTypes(typesArray);
exports.rootValue = merge_graphql_schemas_1.mergeResolvers(resolversArray);
